/**
 * The compiled plugin table, generated by the VRCNext Bridge at `build/static-plugins.ts` and
 * aliased in at bundle time. The repo's own dev build aliases `packages/host/static-plugins.dev.ts`
 * instead. Entries are validated by `readCompiledTable` before use, hence `unknown`.
 */
declare module '@vrcnext/static-plugins' {
  export const COMPILED_PLUGINS: readonly {
    readonly manifest: unknown;
    readonly plugin: unknown;
  }[];
}
