/**
 * The VRCNext page protocol, as its C# source implements it. Generated by
 * scripts/gen-vrcnext-protocol.mjs from https://github.com/shinyflvre/VRCNext at 07ebff1489694270d0e323b5fea67e202b311198.
 * Do not edit; run `npm run protocol:update -- <VRCNext checkout>` instead.
 *
 * Types only: nothing here reaches the bundle. The data, with each event's payload fields where
 * the C# writes them inline, is protocol/vrcnext-protocol.json.
 */

/** Commit of VRCNext these names were read from. */
export type VrcnextSourceCommit = '07ebff1489694270d0e323b5fea67e202b311198';

/** Every action VRCNext's backend dispatches (JS → C#). */
export type VrcnextAction =
  'addAccount' | 'addAccount2FA' | 'addAccountCancel' | 'addFavorite' | 'addFolder'
  | 'afCloseVrchat' | 'afGetGameRunning' | 'afInstanceWebhook' | 'afLoadFlows' | 'afSaveConditions'
  | 'afSaveFlows' | 'afSendChatMessage' | 'afTextWebhook' | 'afTrayNotify' | 'asConnect'
  | 'asDisconnect' | 'asSaveSettings' | 'asSetScale' | 'browseDashBg' | 'browseExe'
  | 'chatboxConfig' | 'chatboxDirectSend' | 'checkRewind' | 'checkUpdate' | 'clearFfcCache'
  | 'commentsApi' | 'consoleCommand' | 'copyImageToClipboard' | 'dbAnalyze' | 'dbBackup'
  | 'dbMemoryUsage' | 'dbOptimize' | 'deleteFriendTimelineByType' | 'deleteFriendTimelineEvent'
  | 'deleteFriendTimelineEvents' | 'deleteLibraryFile' | 'deletePost' | 'deleteTimelineByType'
  | 'deleteTimelineEvent' | 'deleteTimelineEvents' | 'dismissCrashReport' | 'dpStart' | 'dpStop'
  | 'exportDebugKit' | 'exportList' | 'exportSaveCsv' | 'forceFfcAll' | 'forceTrim' | 'fsConfig'
  | 'fsConnect' | 'fsDisconnect' | 'fsGetAudioDevices' | 'fsGetDevices' | 'fsGetFfmpegState'
  | 'fsInstallFfmpeg' | 'fsSetOutput' | 'getApiHealth' | 'getApiHealthDetail' | 'getChangelog'
  | 'getCursorFiles' | 'getCustomThemes' | 'getFriendActivityForUser' | 'getFriendTimeline'
  | 'getFriendTimelineByDate' | 'getFriendTimelinePage' | 'getFtAlsoWasHere' | 'getGameLog'
  | 'getImgCacheSize' | 'getInstanceChart' | 'getMediaTags' | 'getMeetNetwork'
  | 'getMeetNetworkWorlds' | 'getPhotoRating' | 'getProfileInsights' | 'getRewind'
  | 'getSystemFonts' | 'getTimeline' | 'getTimelineByDate' | 'getTimelineForUser'
  | 'getTimelineForWorld' | 'getTimelineMonthActivity' | 'getTimelinePage' | 'getTtsDevices'
  | 'getUserOnlineHeatmap' | 'getUserStatusTime' | 'getWorldInsights' | 'hypeRateGetState'
  | 'importFavorites' | 'importPickFile' | 'importVrcxSelect' | 'importVrcxStart' | 'installUpdate'
  | 'invBrowseUpload' | 'invDeleteFile' | 'invDeletePrint' | 'invDownload' | 'invGetFiles'
  | 'invGetInventory' | 'invGetPrints' | 'invUploadFromData' | 'invUploadPrint' | 'kxdGetDevices'
  | 'kxdLocalCancel' | 'kxdLocalDownload' | 'kxdLocalGetState' | 'kxdLocalSaveSelection'
  | 'kxdLocalUninstall' | 'kxdSaveSettings' | 'kxdStart' | 'kxdStop' | 'kxdTranslateProfileText'
  | 'listAccounts' | 'loadLibraryPage' | 'loadTranslation' | 'logoutAccount' | 'manualPost'
  | 'openLogFile' | 'openLogFolder' | 'openShortcutFolder' | 'openUrl' | 'optimizeImgCache'
  | 'oscConnect' | 'oscDisconnect' | 'oscEnableOutputs' | 'oscSend' | 'oscSendRaw'
  | 'oscSetTabVisible' | 'overlayThemeColors' | 'perminiGet' | 'perminiSave' | 'pickFolder'
  | 'playVRChat' | 'ready' | 'refreshWorldInsights' | 'regBackup' | 'removeAccount'
  | 'removeFavorite' | 'removeMediaUserTag' | 'resetSetup' | 'restartApp' | 'revealInExplorer'
  | 'rewindSeen' | 'saveCustomColors' | 'saveSettings' | 'saveVrcndbConsent' | 'scanLibrary'
  | 'scanLibraryForce' | 'scanLibraryRatings' | 'screenPickColor' | 'searchFriendTimeline'
  | 'searchTimeline' | 'sendCrashReport' | 'setDesktopBackground' | 'setGuiZoom' | 'setMediaTags'
  | 'setMediaUserTag' | 'setPhotoRating' | 'setUserMemo' | 'setupBrowsePhotoDir' | 'setupDone'
  | 'setupReady' | 'setupSaveLanguage' | 'setupSavePhotoDir' | 'setupSavePrefs'
  | 'setupSaveStartWithWindows' | 'setupSaveVrcPath' | 'sfConfig' | 'sfConnect' | 'sfDisconnect'
  | 'sfReset' | 'smartSearchAsk' | 'ssLoadRules' | 'ssSaveRules' | 'ssSetEnabled' | 'stConfig'
  | 'stConnect' | 'stDisconnect' | 'stReset' | 'startRelay' | 'stopRelay' | 'switchAccount'
  | 'trayNotification' | 'ttsPreview' | 'ttsTest' | 'vcCheck' | 'vcInstall' | 'vcStart' | 'vcStop'
  | 'vfAddSound' | 'vfAddSoundToItem' | 'vfDeleteItem' | 'vfDeleteSound' | 'vfGetBlockList'
  | 'vfGetDevices' | 'vfGetItems' | 'vfPlaySound' | 'vfSetBlockList' | 'vfSetInputDevice'
  | 'vfSetOutputDevice' | 'vfSetStopWord' | 'vfSetVolume' | 'vfSetWord' | 'vfStart' | 'vfStop'
  | 'vfStopSound' | 'vrc2FA' | 'vrcAcceptNotification' | 'vrcAddAvatarFavorite'
  | 'vrcAddFavoriteFriend' | 'vrcAddFavoriteFriendToGroup' | 'vrcAddGroupMemberRole'
  | 'vrcAddSdkLogFlag' | 'vrcAddWorldFavorite' | 'vrcBanGroupMember' | 'vrcBatchInvite'
  | 'vrcBlock' | 'vrcBoop' | 'vrcCacheAvatarBatch' | 'vrcCacheDeleteAll' | 'vrcCacheRefresh'
  | 'vrcCacheSweep' | 'vrcCheckAvatars' | 'vrcClearMutualCache' | 'vrcClearNetworkCache'
  | 'vrcClearNotifications' | 'vrcConfigGet' | 'vrcConfigSave' | 'vrcCreateGroup'
  | 'vrcCreateGroupEvent' | 'vrcCreateGroupInstance' | 'vrcCreateGroupPost' | 'vrcCreateGroupRole'
  | 'vrcCreateInstance' | 'vrcCreateLocalGroup' | 'vrcDeleteAvatar' | 'vrcDeleteGroup'
  | 'vrcDeleteGroupEvent' | 'vrcDeleteGroupPost' | 'vrcDeleteGroupRole' | 'vrcDeleteLocalGroup'
  | 'vrcDeleteProfileTheme' | 'vrcDeleteWorld' | 'vrcFollowEvent' | 'vrcFriendFetchStart'
  | 'vrcFriendFetchState' | 'vrcGetActiveWorlds' | 'vrcGetAllModerations' | 'vrcGetAvatarDetail'
  | 'vrcGetAvatarFavGroups' | 'vrcGetAvatarGallery' | 'vrcGetAvatarInfo' | 'vrcGetAvatarStyles'
  | 'vrcGetAvatars' | 'vrcGetBlocked' | 'vrcGetCalendarEvent' | 'vrcGetCalendarEvents'
  | 'vrcGetChatHistory' | 'vrcGetCurrentInstance' | 'vrcGetDashGroupInstances'
  | 'vrcGetFavoriteFriends' | 'vrcGetFavoriteWorlds' | 'vrcGetFriendAlert' | 'vrcGetFriendDetail'
  | 'vrcGetFriendFavGroups' | 'vrcGetFriendPreview' | 'vrcGetGroup' | 'vrcGetGroupBans'
  | 'vrcGetGroupLogs' | 'vrcGetGroupMembers' | 'vrcGetGroupRoleMembers' | 'vrcGetGroupsForNetwork'
  | 'vrcGetHiddenNotifications' | 'vrcGetInstanceAvatars' | 'vrcGetInstanceDetail'
  | 'vrcGetInviteMessages' | 'vrcGetLogFiles' | 'vrcGetMessageTemplates' | 'vrcGetMuted'
  | 'vrcGetMutualsForNetwork' | 'vrcGetMyGroups' | 'vrcGetMyInstances' | 'vrcGetMyWorlds'
  | 'vrcGetNetworkSessions' | 'vrcGetNews' | 'vrcGetNewsArticle' | 'vrcGetNotifications'
  | 'vrcGetOnlineCount' | 'vrcGetPeopleStats' | 'vrcGetPopularWorlds' | 'vrcGetProfileDecorations'
  | 'vrcGetRecentAvatars' | 'vrcGetRecentSeen' | 'vrcGetRecentWorlds' | 'vrcGetRepresentedGroup'
  | 'vrcGetRespondMessages' | 'vrcGetSharedContentInfo' | 'vrcGetTimeSpent' | 'vrcGetUserAvatars'
  | 'vrcGetUserBasic' | 'vrcGetUserFavWorlds' | 'vrcGetVisitedWorlds' | 'vrcGetWorldDetail'
  | 'vrcGetWorldFavGroups' | 'vrcGetWorldInstancesDetail' | 'vrcHideAvatar' | 'vrcHideNotification'
  | 'vrcInteractOff' | 'vrcInteractOn' | 'vrcInviteFriend' | 'vrcInviteFriendWithPhoto'
  | 'vrcInviteToGroup' | 'vrcJoinFriend' | 'vrcJoinGroup' | 'vrcKickGroupMember'
  | 'vrcLaunchAndJoin' | 'vrcLaunchOptionsGet' | 'vrcLaunchOptionsSave' | 'vrcLeaveGroup'
  | 'vrcLoadDashBg' | 'vrcLoadMutualCache' | 'vrcLoadNetworkCache' | 'vrcLogin' | 'vrcLogout'
  | 'vrcLookupAvatarByFileId' | 'vrcMute' | 'vrcMuteChat' | 'vrcOpenInGame' | 'vrcRandomDashBg'
  | 'vrcReadLogFile' | 'vrcRefreshFriends' | 'vrcRemoveAvatarFavorite' | 'vrcRemoveFavoriteFriend'
  | 'vrcRemoveGroupMemberRole' | 'vrcRemoveMyInstance' | 'vrcRemoveWorldFavorite'
  | 'vrcRepresentGroup' | 'vrcRequestInvite' | 'vrcResolveGroups' | 'vrcResolveWorlds'
  | 'vrcRespondToNotification' | 'vrcRespondToNotificationWithPhoto' | 'vrcSaveMutualCache'
  | 'vrcSaveNetworkCache' | 'vrcSaveProfileTheme' | 'vrcSearchAvatars' | 'vrcSearchGroupMembers'
  | 'vrcSearchGroups' | 'vrcSearchUsers' | 'vrcSearchWorlds' | 'vrcSelectAvatar' | 'vrcSelfInvite'
  | 'vrcSendChatMessage' | 'vrcSendFriendRequest' | 'vrcSetActiveProfileTheme'
  | 'vrcSetFriendAlert' | 'vrcSetGroupVisibility' | 'vrcSetHomeWorld' | 'vrcSetProfileDecoration'
  | 'vrcShowAvatar' | 'vrcSnipeStatus' | 'vrcStartSnipe' | 'vrcStopSnipe' | 'vrcUnbanGroupMember'
  | 'vrcUnblock' | 'vrcUnfriend' | 'vrcUnmute' | 'vrcUnmuteChat' | 'vrcUpdateAvatar'
  | 'vrcUpdateBadge' | 'vrcUpdateFavoriteFriendGroup' | 'vrcUpdateFavoriteGroup' | 'vrcUpdateGroup'
  | 'vrcUpdateGroupPost' | 'vrcUpdateGroupRole' | 'vrcUpdateInviteMessage'
  | 'vrcUpdateMessageTemplate' | 'vrcUpdateNote' | 'vrcUpdateProfile'
  | 'vrcUpdateProfileBackground' | 'vrcUpdateProfileBanner' | 'vrcUpdateRespondMessage'
  | 'vrcUpdateStatus' | 'vrcUpdateWorld' | 'vrcUploadAvatarGallery' | 'vrcUploadAvatarImage'
  | 'vrcUploadWorldImage' | 'vrcnPlusCheckEntitlement' | 'vrcnPlusGetTheme' | 'vrcnPlusSaveTheme'
  | 'vroAutoSave' | 'vroCancelRecording' | 'vroCancelScaleRecording' | 'vroConfig' | 'vroConnect'
  | 'vroDisconnect' | 'vroHide' | 'vroRecordKeybind' | 'vroRecordScaleKeybind' | 'vroScaleConfig'
  | 'vroShow' | 'vroToastConfig' | 'vroWaterConfig' | 'weatherGetState' | 'windowBackground'
  | 'windowClose' | 'windowDragStart' | 'windowMaximize' | 'windowMinimize' | 'windowResizeStart'
  | 'wmSurfaceActivate' | 'wmSurfaceClose' | 'wmSurfaceDrag' | 'wmSurfaceOpen' | 'wmSurfaceTitle'
  | 'wmSurfaceVisible';

/** Actions a Linux or macOS build of VRCNext drops before dispatch. */
export type VrcnextWindowsOnlyAction =
  'asConnect' | 'asDisconnect' | 'asSaveSettings' | 'asSetScale' | 'chatboxConfig'
  | 'chatboxDirectSend' | 'dpStart' | 'dpStop' | 'fsConfig' | 'fsConnect' | 'fsDisconnect'
  | 'fsGetAudioDevices' | 'fsGetDevices' | 'fsGetFfmpegState' | 'fsInstallFfmpeg' | 'fsSetOutput'
  | 'kxdGetDevices' | 'kxdLocalCancel' | 'kxdLocalDownload' | 'kxdLocalGetState'
  | 'kxdLocalSaveSelection' | 'kxdLocalUninstall' | 'kxdSaveSettings' | 'kxdStart' | 'kxdStop'
  | 'kxdTranslateProfileText' | 'oscConnect' | 'oscDisconnect' | 'oscEnableOutputs' | 'oscSend'
  | 'oscSendRaw' | 'oscSetTabVisible' | 'sfConfig' | 'sfConnect' | 'sfDisconnect' | 'sfReset'
  | 'stConfig' | 'stConnect' | 'stDisconnect' | 'stReset' | 'startRelay' | 'stopRelay' | 'vcCheck'
  | 'vcInstall' | 'vcStart' | 'vcStop' | 'vfAddSound' | 'vfAddSoundToItem' | 'vfDeleteItem'
  | 'vfDeleteSound' | 'vfGetBlockList' | 'vfGetDevices' | 'vfGetItems' | 'vfPlaySound'
  | 'vfSetBlockList' | 'vfSetInputDevice' | 'vfSetOutputDevice' | 'vfSetStopWord' | 'vfSetVolume'
  | 'vfSetWord' | 'vfStart' | 'vfStop' | 'vfStopSound' | 'vroAutoSave' | 'vroCancelRecording'
  | 'vroCancelScaleRecording' | 'vroConfig' | 'vroConnect' | 'vroDisconnect' | 'vroHide'
  | 'vroRecordKeybind' | 'vroRecordScaleKeybind' | 'vroScaleConfig' | 'vroShow' | 'vroToastConfig'
  | 'vroWaterConfig';

/** Every event type VRCNext's backend sends to the page (C# → JS). */
export type VrcnextEvent =
  'accountAddError' | 'accountAddNeeds2FA' | 'accountAddSuccess' | 'accountSwitchError'
  | 'accountSwitchInProgress' | 'accountSwitchStarting' | 'accountsList' | 'activeWorlds'
  | 'afFlows' | 'afGameRunning' | 'afSaveResult' | 'asState' | 'avtrIcuReport' | 'avtrdbCollecting'
  | 'avtrdbReport' | 'chatboxUpdate' | 'commentsApiResult' | 'consoleOutput' | 'cursorFiles'
  | 'customColors' | 'customThemes' | 'dashBgSelected' | 'dateTimeFormat' | 'dbAnalyzeProgress'
  | 'dbAnalyzeResult' | 'dbBackupDone' | 'dbMemoryResult' | 'dbMigrationProgress'
  | 'dbOptimizeDone' | 'dbOptimizeProgress' | 'debugKitExported' | 'deleteResult' | 'dpState'
  | 'exeAdded' | 'exportList' | 'favoritesLoaded' | 'ffcProgress' | 'filePosted' | 'folderAdded'
  | 'folderPicked' | 'friendActivityForUser' | 'friendOnlineToast' | 'friendTimelineData'
  | 'friendTimelineEvent' | 'friendTimelineEventDeleted' | 'friendTimelineSearchResults'
  | 'fsAudioDevices' | 'fsDevices' | 'fsFfmpegState' | 'fsUpdate' | 'ftAlsoWasHere'
  | 'gameLogEvent' | 'gameLogHistory' | 'groupVisibilityUpdated' | 'hypeRateState'
  | 'imgCacheOptimizeProgress' | 'imgCacheSize' | 'importDone' | 'importFile' | 'importProgress'
  | 'instanceChartData' | 'instanceDetail' | 'invDeleteResult' | 'invFiles' | 'invInventory'
  | 'invPrintDeleteResult' | 'invPrintUploadResult' | 'invPrints' | 'invUploadResult'
  | 'kxdDevices' | 'kxdLocalFinished' | 'kxdLocalProgress' | 'kxdLocalState' | 'kxdMeter'
  | 'kxdProfileTranslated' | 'kxdRecognized' | 'kxdState' | 'kxdTranslated' | 'libraryAuthors'
  | 'libraryData' | 'libraryFileDeleted' | 'libraryNewFile' | 'libraryPageData' | 'libraryRatings'
  | 'libraryWorldIds' | 'loadSettings' | 'log' | 'mediaTagsData' | 'mediaTagsUpdated'
  | 'mediaUserTagsUpdated' | 'meetNetworkData' | 'meetNetworkWorlds' | 'myInstances'
  | 'openDeepLink' | 'oscAvatarParams' | 'oscOutputsEnabled' | 'oscParams' | 'oscState'
  | 'perminiData' | 'photoRating' | 'photoRatingSet' | 'popularWorlds' | 'profileInsights'
  | 'recentAvatars' | 'recentSeenPlayers' | 'recentWorlds' | 'regBackupDone' | 'relayState'
  | 'rewindData' | 'screenPickResult' | 'setPlatform' | 'setupPhotoDirResult' | 'setupState'
  | 'sfUpdate' | 'showChangelog' | 'showCrashModal' | 'smartSearchAnswer' | 'snipeFound'
  | 'snipeJoinResult' | 'snipeStatus' | 'ssApplied' | 'ssRules' | 'ssSaveResult' | 'stUpdate'
  | 'stats' | 'systemFonts' | 'timelineData' | 'timelineEvent' | 'timelineEventDeleted'
  | 'timelineForUser' | 'timelineForWorld' | 'timelineMonthActivity' | 'timelineReload'
  | 'timelineSearchResults' | 'toast' | 'translationData' | 'ttsDevices' | 'updateAvailable'
  | 'updateProgress' | 'updateReady' | 'uptimeTick' | 'userOnlineHeatmap' | 'userStatusTime'
  | 'vcState' | 'vfBlockList' | 'vfDevices' | 'vfItemAdded' | 'vfItems' | 'vfKeyword' | 'vfMeter'
  | 'vfRecognized' | 'vfSoundAdded' | 'vfState' | 'visitedWorlds' | 'vrcActionResult'
  | 'vrcActiveProfileThemeSet' | 'vrcApiHealth' | 'vrcApiHealthDetail' | 'vrcAvatarAnalysis'
  | 'vrcAvatarBatchCached' | 'vrcAvatarBatchDetails' | 'vrcAvatarByFileId'
  | 'vrcAvatarDeleteResult' | 'vrcAvatarDetail' | 'vrcAvatarDetailError' | 'vrcAvatarDetailsBatch'
  | 'vrcAvatarFavGroups' | 'vrcAvatarFavoriteResult' | 'vrcAvatarGallery'
  | 'vrcAvatarGalleryResult' | 'vrcAvatarImageResult' | 'vrcAvatarInfo' | 'vrcAvatarSearchResults'
  | 'vrcAvatarSelected' | 'vrcAvatarStyles' | 'vrcAvatarUnfavoriteResult' | 'vrcAvatarUpdateResult'
  | 'vrcAvatars' | 'vrcAvatarsDeleted' | 'vrcBadgeUpdated' | 'vrcBatchInviteProgress'
  | 'vrcBlockedList' | 'vrcCalendarEvent' | 'vrcCalendarEvents' | 'vrcChatHistory'
  | 'vrcChatMessage' | 'vrcChatSlotInfo' | 'vrcClosed' | 'vrcConfigData' | 'vrcCredits'
  | 'vrcCurrentInstance' | 'vrcDashGroupInstances' | 'vrcFavoriteAvatars'
  | 'vrcFavoriteFriendToggled' | 'vrcFavoriteFriends' | 'vrcFavoriteGroupUpdated'
  | 'vrcFavoriteWorlds' | 'vrcFriendAlertState' | 'vrcFriendDetail' | 'vrcFriendDetailError'
  | 'vrcFriendFacts' | 'vrcFriendFavGroups' | 'vrcFriendFavoriteGroupUpdated'
  | 'vrcFriendFavoriteResult' | 'vrcFriendFetchProgress' | 'vrcFriendPreview' | 'vrcFriendUpdate'
  | 'vrcFriends' | 'vrcGroupBans' | 'vrcGroupCreateResult' | 'vrcGroupDeleteResult'
  | 'vrcGroupDetail' | 'vrcGroupDetailError' | 'vrcGroupInviteProgress' | 'vrcGroupLogs'
  | 'vrcGroupMembersPage' | 'vrcGroupRoleMembers' | 'vrcGroupRoleResult' | 'vrcGroupSearchResults'
  | 'vrcGroupUpdated' | 'vrcGroupsForNetwork' | 'vrcGroupsResolved' | 'vrcHiddenNotifications'
  | 'vrcHideAvatarList' | 'vrcInstanceAvatarFound' | 'vrcInteractOffList'
  | 'vrcInviteMessageUpdateFailed' | 'vrcInviteMessages' | 'vrcLaunchNeeded'
  | 'vrcLaunchOptionsData' | 'vrcLaunched' | 'vrcLocalGroupResult' | 'vrcLogFiles' | 'vrcLogLines'
  | 'vrcLoggedOut' | 'vrcLoginError' | 'vrcMessageTemplateResult' | 'vrcMessageTemplates'
  | 'vrcModDone' | 'vrcMuteChatList' | 'vrcMutedList' | 'vrcMutualCacheLoaded'
  | 'vrcMutualsForNetwork' | 'vrcMyBadges' | 'vrcMyGroups' | 'vrcMyProfile' | 'vrcMyWorlds'
  | 'vrcNeeds2FA' | 'vrcNetworkCacheLoaded' | 'vrcNetworkSessions' | 'vrcNews' | 'vrcNewsArticle'
  | 'vrcNoteUpdated' | 'vrcNotifImageUpdate' | 'vrcNotificationPrepend' | 'vrcNotifications'
  | 'vrcOnlineCount' | 'vrcPeopleStatsData' | 'vrcPrefillLogin' | 'vrcProfileBackgroundUpdated'
  | 'vrcProfileBannerUpdated' | 'vrcProfileDecorations' | 'vrcProfileThemeDeleted'
  | 'vrcProfileThemeSaved' | 'vrcProfileUpdated' | 'vrcRepresentedGroup'
  | 'vrcRespondMessageUpdateFailed' | 'vrcRespondMessages' | 'vrcRunningChanged'
  | 'vrcSearchResults' | 'vrcSelfAppearance' | 'vrcSetProfileDecorationResult'
  | 'vrcSharedContentInfo' | 'vrcTimeSpentData' | 'vrcUnfriendDone' | 'vrcUser' | 'vrcUserAvatars'
  | 'vrcUserBasic' | 'vrcUserFavWorlds' | 'vrcWorldDeleteResult' | 'vrcWorldDetail'
  | 'vrcWorldDetailError' | 'vrcWorldFavGroups' | 'vrcWorldFavoriteResult' | 'vrcWorldImageResult'
  | 'vrcWorldJoined' | 'vrcWorldUnfavoriteResult' | 'vrcWorldUpdateResult' | 'vrcWorldsResolved'
  | 'vrcnPlusEntitlement' | 'vrcnPlusSaveResult' | 'vrcnPlusTheme' | 'vrcndbReport'
  | 'vrcxImportDone' | 'vrcxImportError' | 'vrcxImportProgress' | 'vrcxPreview'
  | 'vrcxSelectCancelled' | 'vroKeybindRecorded' | 'vroPlayToastSound' | 'vroPlayWaterSound'
  | 'vroScaleKeybindRecorded' | 'vroState' | 'vroStopWaterSound' | 'weatherState'
  | 'windowMaxState' | 'wmSurfaceClosed' | 'wmSurfaceCreated' | 'worldInsights'
  | 'worldInstancesDetail' | 'wsStatus';

/**
 * The top-level payload fields of each event whose every sender builds the payload where it can
 * be read (`new { … }`, or a method that returns one). An event missing here sends at least one
 * payload the generator could not see into.
 */
export interface VrcnextEventFields {
  readonly accountAddError:
    'cancelled' | 'error';
  readonly accountAddNeeds2FA:
    'twoFactorType';
  readonly accountAddSuccess:
    'accountId';
  readonly accountSwitchError:
    'action' | 'reason';
  readonly accountSwitchInProgress:
    'rejectedAction';
  readonly accountSwitchStarting:
    'displayName' | 'targetAccountId';
  readonly activeWorlds:
    'worlds';
  readonly afFlows:
    'conditionDefaults' | 'conditions' | 'flows';
  readonly afGameRunning:
    'running';
  readonly afSaveResult:
    'count' | 'error' | 'nonEmpty' | 'ok';
  readonly asState:
    'connected' | 'keyDown' | 'keyUp' | 'scale';
  readonly avtrIcuReport:
    'count' | 'type';
  readonly avtrdbCollecting:
    'count' | 'submit';
  readonly avtrdbReport:
    'count' | 'enqueued' | 'invalid' | 'ticket' | 'type';
  readonly commentsApiResult:
    'data' | 'reqId' | 'status';
  readonly consoleOutput:
    'color' | 'text';
  readonly cursorFiles:
    'files' | 'port';
  readonly customThemes:
    'port' | 'themes';
  readonly dashBgSelected:
    'path' | 'sample' | 'url';
  readonly dateTimeFormat:
    'is24Hour' | 'shortDatePattern';
  readonly dbAnalyzeProgress:
    'running';
  readonly dbAnalyzeResult:
    'avatarSwitchCount' | 'cleanableRows' | 'counts' | 'error' | 'friendAvatarCount'
    | 'friendBioCount' | 'friendOfflineCount' | 'friendOnlineCount' | 'friendRows'
    | 'friendStatusCount' | 'friendStatusDescCount' | 'instancePlayersCount' | 'notificationCount'
    | 'totalRows' | 'videoUrlCount';
  readonly dbBackupDone:
    'error' | 'path';
  readonly dbMemoryResult:
    'error' | 'fileBytes' | 'freeBytes' | 'liveBytes' | 'tables';
  readonly dbMigrationProgress:
    'percent';
  readonly dbOptimizeDone:
    'epCleaned' | 'error' | 'feCleaned' | 'notifCleaned' | 'userCleaned';
  readonly dbOptimizeProgress:
    'phase';
  readonly debugKitExported:
    'error' | 'ok' | 'path';
  readonly deleteResult:
    'messageId' | 'success';
  readonly dpState:
    'running';
  readonly exeAdded:
    'path' | 'target';
  readonly exportList:
    'categories' | 'type';
  readonly ffcProgress:
    'done' | 'label' | 'progress';
  readonly filePosted:
    'channel' | 'messageId' | 'name' | 'size' | 'time' | 'webhookUrl';
  readonly folderPicked:
    'path' | 'target';
  readonly friendActivityForUser:
    'events' | 'userId';
  readonly friendOnlineToast:
    'alertLevel' | 'displayName' | 'image' | 'userId';
  readonly friendTimelineData:
    'date' | 'events' | 'hasMore' | 'offset' | 'total' | 'type';
  readonly friendTimelineEvent:
    'friendId' | 'friendImage' | 'friendName' | 'id' | 'leftAt' | 'location' | 'newValue'
    | 'oldValue' | 'timestamp' | 'tracked' | 'type' | 'worldId' | 'worldName' | 'worldThumb';
  readonly friendTimelineEventDeleted:
    'id';
  readonly friendTimelineSearchResults:
    'date' | 'events' | 'offset' | 'query' | 'total';
  readonly fsAudioDevices:
    'devices' | 'savedA' | 'savedB';
  readonly fsDevices:
    'devices' | 'saved';
  readonly fsFfmpegState:
    'downloading' | 'error' | 'installed' | 'installing' | 'progress';
  readonly ftAlsoWasHere:
    'excludeId' | 'friends';
  readonly gameLogEvent:
    'detail' | 'message' | 'timestamp' | 'type';
  readonly gameLogHistory:
    'entries';
  readonly groupVisibilityUpdated:
    'groupId' | 'success' | 'visibility';
  readonly hypeRateState:
    'available' | 'bpm' | 'connected' | 'error';
  readonly imgCacheOptimizeProgress:
    'done' | 'total';
  readonly imgCacheSize:
    'bytes';
  readonly importDone:
    'failed' | 'ok' | 'skipped' | 'total' | 'type';
  readonly importFile:
    'groups' | 'text' | 'type';
  readonly importProgress:
    'done' | 'failed' | 'ok' | 'skipped' | 'total' | 'type';
  readonly instanceChartData:
    'date' | 'events';
  readonly instanceDetail:
    'capacity' | 'error' | 'instanceType' | 'location' | 'ownerGroup' | 'ownerId' | 'ownerName'
    | 'userCount' | 'worldId' | 'worldName' | 'worldThumb';
  readonly invDeleteResult:
    'fileId' | 'success';
  readonly invFiles:
    'error' | 'files' | 'tag';
  readonly invPrintDeleteResult:
    'printId' | 'success';
  readonly invPrintUploadResult:
    'error' | 'printId' | 'success';
  readonly invPrints:
    'error' | 'prints';
  readonly invUploadResult:
    'error' | 'file' | 'success' | 'tag';
  readonly kxdDevices:
    'apiKey' | 'blockSentences' | 'blockWords' | 'chatboxNotify' | 'devices' | 'disableNonSpeech'
    | 'googleApiKey' | 'input' | 'localLlmModel' | 'localSttModel' | 'localUseGpu'
    | 'localVadEnabled' | 'model' | 'noiseGatePct' | 'oscEnabled' | 'partialOsc' | 'personality'
    | 'profileTargetLang' | 'profileTranslationEnabled' | 'sourceLang' | 'targetLang'
    | 'translateEnabled' | 'tts' | 'ttsDevices' | 'ttsEnabled' | 'ttsEngine' | 'ttsRate' | 'ttsVoice'
    | 'ttsVoices';
  readonly kxdLocalFinished:
    'error' | 'id' | 'ok';
  readonly kxdLocalProgress:
    'done' | 'id' | 'pct' | 'total';
  readonly kxdLocalState:
    'items' | 'root' | 'vulkanAvailable';
  readonly kxdMeter:
    'level';
  readonly kxdProfileTranslated:
    'error' | 'ok' | 'reqId' | 'text';
  readonly kxdRecognized:
    'isPartial' | 'text';
  readonly kxdState:
    'running';
  readonly kxdTranslated:
    'text';
  readonly libraryData:
    'files' | 'hasMore' | 'total';
  readonly libraryFileDeleted:
    'path';
  readonly libraryNewFile:
    'authorId' | 'authorName' | 'folder' | 'modified' | 'name' | 'path' | 'players' | 'size' | 'time'
    | 'type' | 'url' | 'worldId';
  readonly libraryPageData:
    'files' | 'hasMore' | 'offset' | 'total';
  readonly mediaTagsData:
    'catalog' | 'tags' | 'userTags';
  readonly mediaTagsUpdated:
    'path' | 'tags';
  readonly mediaUserTagsUpdated:
    'path' | 'userTags';
  readonly meetNetworkData:
    'people';
  readonly meetNetworkWorlds:
    'userId' | 'worlds';
  readonly openDeepLink:
    'action' | 'id' | 'prefix';
  readonly oscAvatarParams:
    'avatarId' | 'paramList';
  readonly oscOutputsEnabled:
    'filesUpdated';
  readonly oscParams:
    'list' | 'render';
  readonly oscState:
    'connected';
  readonly photoRating:
    'path' | 'stars';
  readonly photoRatingSet:
    'ok' | 'path' | 'stars';
  readonly popularWorlds:
    'worlds';
  readonly profileInsights:
    'persons' | 'userId' | 'worlds';
  readonly recentAvatars:
    'avatars';
  readonly recentSeenPlayers:
    'players';
  readonly recentWorlds:
    'worlds';
  readonly regBackupDone:
    'error' | 'path';
  readonly relayState:
    'running' | 'streams';
  readonly screenPickResult:
    'cancelled' | 'hex' | 'unsupported';
  readonly setPlatform:
    'isLinux';
  readonly setupState:
    'displayName' | 'language' | 'loggedIn' | 'photoDir' | 'platform' | 'prefs' | 'startWithSystem'
    | 'vrcPath';
  readonly showCrashModal:
    'preview';
  readonly smartSearchAnswer:
    'alternatives' | 'answer' | 'ok' | 'reqId' | 'slug' | 'title';
  readonly snipeFound:
    'accessType' | 'capacity' | 'instanceId' | 'location' | 'userCount' | 'worldId' | 'worldName';
  readonly snipeJoinResult:
    'error' | 'location' | 'method' | 'success';
  readonly snipeStatus:
    'accessTypes' | 'active' | 'autoJoin' | 'backoffMs' | 'error' | 'groupId' | 'minCapacity'
    | 'rateLimited' | 'worldId';
  readonly ssApplied:
    'message' | 'restored' | 'ruleId' | 'status';
  readonly ssRules:
    'activeRuleId' | 'enabled' | 'rules' | 'vrcRunning';
  readonly ssSaveResult:
    'count' | 'error' | 'ok';
  readonly stats:
    'files' | 'size';
  readonly systemFonts:
    'fonts';
  readonly timelineData:
    'date' | 'events' | 'hasMore' | 'offset' | 'total' | 'type';
  readonly timelineEventDeleted:
    'id';
  readonly timelineForUser:
    'events' | 'userId';
  readonly timelineForWorld:
    'events' | 'worldId';
  readonly timelineMonthActivity:
    'days' | 'month' | 'year';
  readonly timelineReload:
    'mode';
  readonly timelineSearchResults:
    'date' | 'events' | 'offset' | 'query' | 'total';
  readonly toast:
    'msg' | 'ok';
  readonly translationData:
    'language' | 'translations';
  readonly ttsDevices:
    'devices' | 'engine' | 'target' | 'voices';
  readonly updateAvailable:
    'version';
  readonly userOnlineHeatmap:
    'buckets' | 'days' | 'sessions' | 'totalMinutes' | 'userId';
  readonly userStatusTime:
    'buckets' | 'days' | 'totalSeconds' | 'totals' | 'userId';
  readonly vcState:
    'downloading' | 'error' | 'installed' | 'progress' | 'running';
  readonly vfBlockList:
    'words';
  readonly vfDevices:
    'input' | 'inputs' | 'output' | 'outputs' | 'stopWord';
  readonly vfItemAdded:
    'files' | 'index' | 'word';
  readonly vfKeyword:
    'word';
  readonly vfMeter:
    'level';
  readonly vfRecognized:
    'isPartial' | 'text';
  readonly vfSoundAdded:
    'durationMs' | 'fileName' | 'filePath' | 'itemIndex' | 'soundIndex' | 'volumePercent';
  readonly vfState:
    'running';
  readonly visitedWorlds:
    'worlds';
  readonly vrcActionResult:
    'action' | 'eventId' | 'groupId' | 'groupJoined' | 'location' | 'message' | 'postId' | 'roleId'
    | 'success' | 'userId';
  readonly vrcActiveProfileThemeSet:
    'success' | 'themeId';
  readonly vrcApiHealth:
    'description' | 'indicator' | 'updatedAt';
  readonly vrcApiHealthDetail:
    'componentGroups' | 'description' | 'errors' | 'incidents' | 'indicator' | 'latency'
    | 'latencyMs' | 'onlineUsers' | 'requests' | 'visits';
  readonly vrcAvatarAnalysis:
    'avatarId' | 'cached' | 'pending' | 'platforms';
  readonly vrcAvatarByFileId:
    'avatarAuthor' | 'avatarId' | 'avatarImage' | 'avatarName' | 'avatarUnresolved' | 'fileId'
    | 'openModal' | 'userId';
  readonly vrcAvatarDeleteResult:
    'avatarId' | 'error' | 'ok';
  readonly vrcAvatarDetail:
    'authorId' | 'authorName' | 'created_at' | 'description' | 'hasImpostor' | 'hasIos' | 'hasPC'
    | 'hasQuest' | 'id' | 'imageUrl' | 'impostorVersion' | 'iosPerf' | 'name' | 'pcPerf'
    | 'questPerf' | 'rawJson' | 'releaseStatus' | 'stylePrimary' | 'styleSecondary' | 'tags'
    | 'thumbnailImageUrl' | 'updated_at' | 'version';
  readonly vrcAvatarDetailError:
    'error';
  readonly vrcAvatarFavoriteResult:
    'avatarId' | 'error' | 'groupName' | 'newFvrtId' | 'ok';
  readonly vrcAvatarGallery:
    'avatarId' | 'images';
  readonly vrcAvatarGalleryResult:
    'avatarId' | 'error' | 'images' | 'ok';
  readonly vrcAvatarImageResult:
    'avatarId' | 'error' | 'imageUrl' | 'ok';
  readonly vrcAvatarInfo:
    'avatarAuthor' | 'avatarId' | 'avatarImage' | 'avatarName' | 'context' | 'userId';
  readonly vrcAvatarSearchResults:
    'hasMore' | 'page' | 'results';
  readonly vrcAvatarSelected:
    'avatarId';
  readonly vrcAvatarUnfavoriteResult:
    'avatarId' | 'ok';
  readonly vrcAvatarUpdateResult:
    'avatarId' | 'description' | 'error' | 'name' | 'ok' | 'releaseStatus' | 'stylePrimary'
    | 'styleSecondary' | 'tags';
  readonly vrcAvatarsDeleted:
    'ids';
  readonly vrcBadgeUpdated:
    'badgeId' | 'showcased' | 'success';
  readonly vrcBatchInviteProgress:
    'done' | 'fail' | 'success' | 'total';
  readonly vrcCalendarEvents:
    'events' | 'filter';
  readonly vrcChatHistory:
    'messages' | 'userId';
  readonly vrcChatSlotInfo:
    'total' | 'used';
  readonly vrcClosed: never;
  readonly vrcConfigData:
    'cacheBytes' | 'config' | 'inGame' | 'prints' | 'stickers';
  readonly vrcCredits:
    'balance';
  readonly vrcCurrentInstance:
    'ageGate' | 'capacity' | 'displayName' | 'empty' | 'error' | 'instanceType' | 'location'
    | 'minAvatarPerf' | 'nUsers' | 'ownerGroup' | 'ownerId' | 'ownerName' | 'playerSource' | 'users'
    | 'worldId' | 'worldName' | 'worldThumb';
  readonly vrcFavoriteFriendToggled:
    'fvrtId' | 'groupName' | 'isFavorited' | 'userId';
  readonly vrcFavoriteGroupUpdated:
    'displayName' | 'groupName' | 'ok' | 'visibility';
  readonly vrcFriendAlertState:
    'level' | 'userId';
  readonly vrcFriendDetailError:
    'error';
  readonly vrcFriendFacts:
    'bioLinks' | 'dateJoined' | 'id' | 'lastActivity' | 'lastLogin' | 'lastSeen' | 'mutualFriends'
    | 'mutualGroups' | 'pronouns';
  readonly vrcFriendFavoriteGroupUpdated:
    'displayName' | 'groupName' | 'ok' | 'visibility';
  readonly vrcFriendFavoriteResult:
    'error' | 'groupName' | 'newFvrtId' | 'ok' | 'userId';
  readonly vrcFriendFetchProgress:
    'cooldownMs' | 'done' | 'running' | 'total';
  readonly vrcFriendPreview:
    'backgroundGradientBottom' | 'backgroundGradientTop' | 'backgroundTextureId'
    | 'backgroundTextureUrl' | 'backgroundType' | 'bannerColor' | 'bannerType' | 'bannerUrl' | 'bio'
    | 'id' | 'profilePicOverride' | 'themeButtonColor' | 'themeIconColor' | 'themeSubtextColor';
  readonly vrcFriendUpdate:
    'ageVerificationStatus' | 'ageVerified' | 'avatarFileId' | 'badges' | 'bannerColor'
    | 'bannerType' | 'bannerUrl' | 'bio' | 'bioLinks' | 'currentAvatarImageUrl' | 'dateJoined'
    | 'displayName' | 'iconFrame' | 'iconFrameUrl' | 'id' | 'image' | 'instanceType'
    | 'isEconomyCreator' | 'isFriend' | 'lastActivity' | 'lastLogin' | 'lastSeen' | 'location'
    | 'mutualFriends' | 'mutualGroups' | 'nameplateEffect' | 'nameplateUrl' | 'pendingOffline'
    | 'platform' | 'presence' | 'profileEffect' | 'profileEffectUrl' | 'profilePicOverride'
    | 'pronouns' | 'status' | 'statusDescription' | 'tags' | 'traveling' | 'worldName' | 'worldThumb';
  readonly vrcFriends:
    'counts' | 'friends';
  readonly vrcGroupBans:
    'bans' | 'groupId';
  readonly vrcGroupCreateResult:
    'error' | 'groupId' | 'ok' | 'vrcPlusRequired';
  readonly vrcGroupDeleteResult:
    'error' | 'groupId' | 'ok';
  readonly vrcGroupDetail:
    'bannerUrl' | 'canAssignRoles' | 'canBan' | 'canEdit' | 'canEvent' | 'canInvite' | 'canKick'
    | 'canManageRoles' | 'canPost' | 'canViewAudit' | 'createdAt' | 'description' | 'galleryImages'
    | 'groupEvents' | 'groupInstances' | 'groupMembers' | 'iconUrl' | 'id' | 'isJoined'
    | 'isRepresenting' | 'isVerified' | 'joinState' | 'joinedAt' | 'languages' | 'links'
    | 'memberCount' | 'myRoleIds' | 'name' | 'onlineMemberCount' | 'ownerDisplayName' | 'ownerId'
    | 'posts' | 'privacy' | 'rawJson' | 'roles' | 'rules' | 'shortCode' | 'visibility';
  readonly vrcGroupDetailError:
    'error';
  readonly vrcGroupInviteProgress:
    'done' | 'error' | 'fail' | 'success' | 'total';
  readonly vrcGroupLogs:
    'error' | 'groupId' | 'hasNext' | 'logs' | 'offset' | 'totalCount';
  readonly vrcGroupMembersPage:
    'groupId' | 'hasMore' | 'members' | 'offset';
  readonly vrcGroupRoleMembers:
    'groupId' | 'members' | 'roleId';
  readonly vrcGroupRoleResult:
    'action' | 'groupId' | 'role' | 'roleId' | 'success';
  readonly vrcGroupSearchResults:
    'groupId' | 'members' | 'query';
  readonly vrcGroupUpdated:
    'bannerId' | 'description' | 'groupId' | 'iconId' | 'joinState' | 'languages' | 'links' | 'rules'
    | 'success';
  readonly vrcGroupsForNetwork:
    'groups' | 'userId';
  readonly vrcInstanceAvatarFound:
    'avatarId' | 'avatarName' | 'userId';
  readonly vrcInviteMessageUpdateFailed:
    'cooldown' | 'slot';
  readonly vrcLaunchNeeded:
    'location' | 'steamVr';
  readonly vrcLaunchOptionsData:
    'args' | 'path';
  readonly vrcLaunched:
    'vr';
  readonly vrcLocalGroupResult:
    'action' | 'displayName' | 'error' | 'groupName' | 'kind' | 'ok';
  readonly vrcLogFiles:
    'dir' | 'error' | 'files';
  readonly vrcLogLines:
    'categories' | 'entries' | 'error' | 'file' | 'matched' | 'total' | 'truncated';
  readonly vrcLoginError:
    'error';
  readonly vrcMessageTemplateResult:
    'cooldown' | 'ok' | 'pool' | 'slot';
  readonly vrcMessageTemplates:
    'error' | 'messages' | 'pool';
  readonly vrcModDone:
    'active' | 'type' | 'userId';
  readonly vrcMutualCacheLoaded:
    'json';
  readonly vrcMutualsForNetwork:
    'mutualIds' | 'optedOut' | 'userId';
  readonly vrcMyBadges:
    'badges';
  readonly vrcMyProfile:
    'bio' | 'bioLinks' | 'languages';
  readonly vrcNeeds2FA:
    'type';
  readonly vrcNetworkCacheLoaded:
    'json' | 'name';
  readonly vrcNetworkSessions:
    'pairs';
  readonly vrcNews:
    'items';
  readonly vrcNewsArticle:
    'error' | 'html' | 'id' | 'link' | 'port' | 'title';
  readonly vrcNoteUpdated:
    'note' | 'success' | 'userId';
  readonly vrcNotifImageUpdate:
    'image' | 'notifId' | 'senderUsername';
  readonly vrcOnlineCount:
    'count';
  readonly vrcPeopleStatsData:
    'stats';
  readonly vrcPrefillLogin:
    'password' | 'username';
  readonly vrcProfileBackgroundUpdated:
    'backgroundGradientBottom' | 'backgroundGradientTop' | 'backgroundTextureId'
    | 'backgroundTextureUrl' | 'backgroundType' | 'success';
  readonly vrcProfileBannerUpdated:
    'bannerUrl' | 'success';
  readonly vrcProfileDecorations:
    'decorations';
  readonly vrcProfileThemeDeleted:
    'success' | 'themeId';
  readonly vrcProfileThemeSaved:
    'created' | 'success' | 'theme';
  readonly vrcProfileUpdated:
    'bio' | 'bioLinks' | 'error' | 'languages' | 'pronouns' | 'success';
  readonly vrcRespondMessageUpdateFailed:
    'cooldown' | 'pool' | 'slot';
  readonly vrcRespondMessages:
    'messages' | 'pool';
  readonly vrcRunningChanged:
    'running';
  readonly vrcSearchResults:
    'hasMore' | 'offset' | 'results' | 'type';
  readonly vrcSelfAppearance:
    'backgroundGradientBottom' | 'backgroundGradientTop' | 'backgroundTextureId'
    | 'backgroundTextureUrl' | 'backgroundType' | 'bannerColor' | 'bannerType' | 'themeId' | 'themes';
  readonly vrcSetProfileDecorationResult:
    'field' | 'ok' | 'url' | 'value';
  readonly vrcSharedContentInfo:
    'contentId' | 'contentType' | 'image' | 'name';
  readonly vrcTimeSpentData:
    'allUniqueGroups' | 'allUniquePersons' | 'allUniqueWorlds' | 'globalFriendCount'
    | 'globalGroupJoins' | 'globalGroupSeconds' | 'globalStrangerCount' | 'globalTopFriendName'
    | 'globalTopFriendSeconds' | 'globalTopGroupName' | 'globalTopStrangerName'
    | 'globalTopStrangerSeconds' | 'globalTopWorldName' | 'globalTotalVisits'
    | 'globalTotalWithOthers' | 'groups' | 'maxGroupSeconds' | 'maxPersonSeconds' | 'maxWorldSeconds'
    | 'page' | 'persons' | 'reqId' | 'totalGroups' | 'totalPersons' | 'totalSeconds' | 'totalWorlds'
    | 'worlds';
  readonly vrcUnfriendDone:
    'userId';
  readonly vrcUser:
    'ageVerificationStatus' | 'ageVerified' | 'allowAvatarCopying' | 'bannerColor' | 'bannerType'
    | 'bannerUrl' | 'bio' | 'bioLinks' | 'currentAvatar' | 'currentAvatarImageUrl' | 'dateJoined'
    | 'displayName' | 'homeLocation' | 'iconFrame' | 'iconFrameUrl' | 'id' | 'image'
    | 'isBoopingEnabled' | 'isEconomyCreator' | 'lastLogin' | 'lastPlatform' | 'nameplateEffect'
    | 'nameplateUrl' | 'platform' | 'profileEffect' | 'profileEffectUrl' | 'profilePicOverride'
    | 'pronouns' | 'rawJson' | 'status' | 'statusDescription' | 'statusHistory' | 'tags'
    | 'vrcRunning';
  readonly vrcUserAvatars:
    'avatars' | 'userId';
  readonly vrcUserBasic:
    'contextId' | 'displayName' | 'id' | 'image' | 'status' | 'statusDescription';
  readonly vrcWorldDeleteResult:
    'error' | 'ok' | 'worldId';
  readonly vrcWorldDetail:
    'androidSize' | 'authorId' | 'authorName' | 'capacity' | 'createdAt' | 'description'
    | 'favorites' | 'fromCache' | 'heat' | 'id' | 'imageUrl' | 'instances' | 'iosSize' | 'name'
    | 'occupants' | 'pcSize' | 'popularity' | 'privateOccupants' | 'publicOccupants' | 'rawJson'
    | 'recommendedCapacity' | 'tags' | 'thumbnailImageUrl' | 'updatedAt' | 'version' | 'visits'
    | 'worldTimeSeconds' | 'worldVisitCount';
  readonly vrcWorldDetailError:
    'error';
  readonly vrcWorldFavoriteResult:
    'error' | 'groupName' | 'newFvrtId' | 'ok' | 'worldId';
  readonly vrcWorldImageResult:
    'error' | 'imageUrl' | 'ok' | 'worldId';
  readonly vrcWorldJoined:
    'worldId';
  readonly vrcWorldUnfavoriteResult:
    'ok' | 'worldId';
  readonly vrcWorldUpdateResult:
    'description' | 'error' | 'name' | 'ok' | 'tags' | 'worldId';
  readonly vrcnPlusEntitlement:
    'isPlus' | 'userId';
  readonly vrcnPlusSaveResult:
    'error' | 'ok' | 'theme' | 'userId';
  readonly vrcnPlusTheme:
    'source' | 'theme' | 'userId';
  readonly vrcndbReport:
    'count' | 'duplicates' | 'enqueued' | 'type';
  readonly vrcxImportDone:
    'friendEvents' | 'friends' | 'meetEvents' | 'timelineJoins' | 'worlds';
  readonly vrcxImportError:
    'error';
  readonly vrcxImportProgress:
    'percent' | 'status';
  readonly vrcxPreview:
    'bios' | 'friendTimes' | 'gps' | 'locations' | 'onlineOffline' | 'path' | 'statuses' | 'worlds';
  readonly vroKeybindRecorded:
    'hand' | 'ids' | 'mode' | 'names';
  readonly vroPlayToastSound: never;
  readonly vroPlayWaterSound: never;
  readonly vroScaleKeybindRecorded:
    'hand' | 'ids' | 'names';
  readonly vroStopWaterSound: never;
  readonly weatherState:
    'city' | 'error' | 'ok' | 'text';
  readonly wmSurfaceClosed:
    'wmId';
  readonly wmSurfaceCreated:
    'surfaceId' | 'wmId';
  readonly worldInsights:
    'from' | 'stats' | 'to' | 'worldId';
  readonly worldInstancesDetail:
    'instances' | 'world' | 'worldId';
  readonly wsStatus:
    'connected';
}
